server:
  port: 8081
spring:
  application:
    name: HelloProvider  #项目名 服务名
  cloud:
    nacos:
      discovery:
        server-addr: http://10.8.163.44:8848/ #注册中心的地址
  datasource:
      url: jdbc:mysql://localhost:3306/db_cloud2005?serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource

